language: go
go:
- 1.11.x
sudo: required
services:
- docker
script:
- export GO111MODULE=on
- make setup linter-install
- make ci
- make
after_success:
- export REPO=navitia/sytralrt
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- make docker
- docker tag $REPO:$(make version) $REPO:$TAG
- docker tag $REPO:$(make version) $REPO:travis-$TRAVIS_BUILD_NUMBER
- if [ -n $TRAVIS_TAG ]; then  $REPO:$(make version) $REPO:$TRAVIS_TAG; fi
- if [ -n "$DOCKER_USER" ] && [ -n "$DOCKER_PASS" ]; then docker login -u $DOCKER_USER -p $DOCKER_PASS && docker push $REPO; fi
env:
  global:
    - secure: "nqogy5+VrUS6Yd0hacOip0uY4KbQ3HN+I419uyFwCM6ep40f4m4NjxqYyAruBdReGnpravi6OnwzYG/pUQ2f08OHRqBFf2lZnvyZNW8e2sPYcoIrK2npWIsc4Bpm3G1xQ9+HtMRTYXoWLROCBYMzOaT+OqHaZxWI4Wt8VLOBEoGke4izdd4mRh03j5ICVAbyI6nlyYW3bK0tiKUYyQmN1hGXrTwKzWdjtLOEPidlEzPsKh6vA+803PohyV/R9nKLa/9DNq/X9UEFJoLPm66bJsKt8jmsn2MxobHoquokWdsV69s7kulgHjkjUtJSgoXMTvS3hMt4Qii53VhRHn9x6dZFJAxUmqGOGP2+dxYJCygYq3El5MfRmGb7XGRg375ObbEOh+WHMIHuDSY48fN1i9S66lZy7vKEdPGKZDWc8y0A060KYTcEEVJB1Np/Er8TC3ogJ9fmmiaUBY+XQ9/iNDfzpyPBALt42F9F09R2lLAOk98BXZz9J4+dqFBZGzdjKvLCXdvnPxkoZHGfsFhRTC4keJj43fl3hEmWIvVbgpg+kGydCzxBWlAMtVE9FFKxUkiF3DnJdpzXe9e1Eze9zGFFnmGP1pk1f+HNK1DI9JxgicXUfVQu75nX17gSnh60KDTv38qM/38iAcd5hQ/P84qgBPcQsfcV984EkhbffGc="
    - secure: "u7AVxnKY2hTJXY/R1SVdstA+26ZytcWh2I8H0JWsbDkYEnWHHA3YurkDVtTVJg1/lMQBMHFHbzO8WEXNp2jS6aBCts2DtwG8nY/JzaClwRRefueXm4Ss5CxdZPnB72qRuSgYvJmf4zYTiiUyrTPCm3yO72wSHgUs65+xe/9Iqu9CokJQgXyPZNk3c9IJaqdm1QR2hbLGkGE4WR8JePWZigGIq8RH89nZJ8Qf8nDgdUtlrZHN3/AjkfnKhcANxgidjdyLhGLc5AII6STDnoyK2KRe41Wbth0rg14ZiHPmKJzPclhGclc3fL3im6RXAQRqazhLMuXf/w1P0j1O1QOM2NZ8ASZ2PNP4M4tfmR4mKhjFaaxa6IFpiDvaeW+LPgrHC+XUKfIIcYhKUIJgeEVdkltpI0OGXfr8y3sx6IGx6T5QwsWFq8xIsbR13KAeyknHTrkmvHIBHFtxlsDBkZWX7OTkQRH1eZga/wvuRtb0G+A2zU6eLJnZ8FEdTzBOa81SdY6SXPmXC8j+wRkCqDwBqGpUBPP7JVDCfOcPuxOb4CoN3Vmxv0EjlvKo4updOXsgv88hOHeWwKXNWlpdsNEmdTBfoHkk5uFXm+OYKb9LcVCg8Mr4uHShFgOzPdbAfPnO8m/JUmy9T6wl9jsfn3unB0Wo7BP5c8J0KjGKRr7lK+Y=" #DOCKER_USER
