name: Create and publish master image

on:
  push:
    branches:
      - master

jobs:
  CreateAndPublish:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: install zip dependency
        run: apt update && apt install -y zip httpie

      - name: Build a version
        run: make build

      - name: create publish release images
        run: |
          make docker
          make dockerhub-login DOCKER_USER=${{secrets.DOCKERHUB_USER}} DOCKER_PASSWORD=${{secrets.DOCKERHUB_PWD}}
          make push-image-forseti-master

      - name: slack notification (the job has failed)
        if: failure()
        run: |
          echo '{"text":":Warning: Github Actions: Create image for branch master failed ! (https://github.com/CanalTP/forseti/actions/workflows/master.yml)."}' | http --json POST ${{secrets.SLACK_NAVITIA_CORE_TEAM_URL}}
