name: CI

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.11.x]
        os: [ubuntu-16.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare Env
        run: export GO111MODULE=on

      - name: Install all the build and lint dependencies
        run: make setup

      - name: Install linter
        run: make linter-install

      - name: Run all the tests and code checks
        run: make ci
